# listen port
port: 8101

# Secret signature salt
signature_salt: 'secret'

# Signature algorithm, use md5 or murmur
signature_algorithm: 'murmur'

# Enforce Webp
enforce_webp: true

# padding value for add padding cast
padding: 10

# default quality for images
quality_default: 80

# quality for different formats
quality:
  - format: jpg
    quality: 80
    conditions:
      - from: 0
        to: 1000
        quality: 90
      - from: 1000
        to: 1800
        quality: 85
  - format: webp
    quality: 80
    conditions:
      - from: 0
        to: 1000
        quality: 90
      - from: 1000
        to: 1800
        quality: 85
  - format: png
    quality: 80 # any less than 100 to quantize
    iterations: 200 # zopfli iterations, 0 not to zopflify
    conditions:
      - from: 0
        to: 500
        quality: 100
        iterations: 500