version: "3"

services:
  gokaru:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          MODULE_PATH: github.com/urvin/gokaru
    environment:
      - GOKARU_STORAGE_PATH=/var/gokaru_storage/
    ports:
      - "8101:8101"
    restart: unless-stopped
    volumes:
      - "./:/go/src/github.com/urvin/gokaru"
      - "./storage/:/var/gokaru_storage/"
      - "./logs/:/var/log/gokaru/"